use std::{
    collections::HashSet,
    env,
    fs::{self, File},
    io::Write,
    path::PathBuf,
};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing manifest dir"));
    let scripts_dir = manifest_dir.join("scripts");
    println!("cargo:rerun-if-changed={}", scripts_dir.display());

    if !scripts_dir.is_dir() {
        panic!("scripts directory missing: {}", scripts_dir.display());
    }

    let mut scripts = Vec::new();
    for entry in fs::read_dir(&scripts_dir).expect("failed to read scripts directory") {
        let entry = entry.expect("failed to read scripts directory entry");
        let path = entry.path();
        println!("cargo:rerun-if-changed={}", path.display());
        if path.extension().and_then(|ext| ext.to_str()) == Some("rhai") {
            scripts.push(path);
        }
    }

    scripts.sort();
    if scripts.is_empty() {
        panic!("no Rhai scripts found in {}", scripts_dir.display());
    }

    let mut generated = String::from("// @generated by build.rs; do not edit\n\n");
    let mut seen_idents = HashSet::new();
    for script in scripts {
        let file_stem = script
            .file_stem()
            .and_then(|stem| stem.to_str())
            .unwrap_or("script");
        let mut ident = format!("compile_{}", sanitize_identifier(file_stem));
        while !seen_idents.insert(ident.clone()) {
            ident.push('_');
        }

        let relative = script
            .strip_prefix(&manifest_dir)
            .unwrap_or(&script)
            .to_str()
            .expect("failed to stringify script path");
        generated.push_str(&format!(
            "#[test]\nfn {ident}() {{\n    compile_script(Path::new(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{relative}\")));\n}}\n\n"
        ));
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR missing"));
    let dest = out_dir.join("rhai_script_tests.rs");
    let mut file = File::create(dest).expect("failed to create generated test file");
    file.write_all(generated.as_bytes())
        .expect("failed to write generated test file");
}

fn sanitize_identifier(name: &str) -> String {
    let mut ident = String::new();
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            ident.push(ch.to_ascii_lowercase());
        } else {
            ident.push('_');
        }
    }

    let ident = ident.trim_matches('_').to_string();
    if ident.is_empty() {
        "script".to_string()
    } else {
        ident
    }
}
