apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: hello
          image: busybox:stable
          command: ["sh", "-c", "echo 'Hello from Kubernetes Job'; sleep 5"]
  backoffLimit: 2
