// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BuildCacheSettings = { include: Array<string>, exclude: Array<string>, home_include: Array<string>, home_exclude: Array<string>, max_entries_per_repo?: number | null, };
