// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A validated document path that enforces structural constraints:
 * - Must not be empty
 * - Must start with `/` (normalized on construction)
 * - No empty segments (e.g. `foo//bar`)
 * - No hidden segments (path components starting with `.`)
 */
export type DocumentPath = string;
