packages:
  - "packages/api"
  - "packages/mock-server"
  - "packages/ui"
  - "packages/web"
onlyBuiltDependencies:
  - "esbuild"
minimumReleaseAge: 10080
minimumReleaseAgeExclude: []
allowBuilds:
  esbuild: set this to true or false
