import { useCallback, useEffect, useMemo, useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import {
  Avatar,
  Button,
  ColorPicker,
  Icons,
  Input,
  Modal,
  Picker,
  PickerRow,
  Select,
  Textarea,
} from "@hydra/ui";
import type {
  DocumentPath,
  ListProjectsResponse,
  Principal,
  ProjectRecord,
  SessionSettings,
  StatusDefinition,
  StatusOnEnter,
  Timeout,
} from "@hydra/api";
import { apiClient } from "../../api/client";
import { useToast } from "../toast/useToast";
import { useAgents } from "../../hooks/useAgents";
import { useUsers } from "../../hooks/useUsers";
import { LABEL_COLOR_PALETTE } from "../../components/ColorPicker";
import { PROJECTS_QUERY_KEY, applyOptimisticUpsert } from "./projectCache";
import {
  AUTO_ARCHIVE_UNIT_SECONDS,
  blankStatus,
  deriveAutoArchiveDisplay,
  readAutoArchiveSeconds,
  slugifyStatusKey,
  type AutoArchiveUnit,
} from "./statusDefaults";
import { upsertPromptDoc, usePromptDocumentBody } from "./promptDocument";
import { DeleteConfirmModal } from "../../components/DeleteConfirmModal/DeleteConfirmModal";
import styles from "./StatusSettingsModal.module.css";

export interface StatusSettingsModalProps {
  open: boolean;
  onClose: () => void;
  projectRecord: ProjectRecord;
  /** Defaults to "edit". In "new" mode `statusKey`/`issueCount` are ignored. */
  mode?: "edit" | "new";
  /** Required in edit mode; ignored in new mode. */
  statusKey?: string;
  /** Required in edit mode; ignored in new mode. */
  issueCount?: number;
}

/**
 * Derive a status key from its display name and validate it against the keys
 * already in use. The key is never shown to the user — it is generated by
 * slugifying the name so the two stay in sync in both the Add and Edit flows.
 * `reservedKeys` should exclude the status being edited so re-saving without a
 * rename keeps its own key. Returns `{ key, error }`; `error` is null when the
 * derived key is usable (an empty name yields a null error here — callers gate
 * Save on a non-empty name separately).
 */
function deriveKeyAndError(
  name: string,
  reservedKeys: ReadonlySet<string>,
): { key: string; error: string | null } {
  const key = slugifyStatusKey(name);
  if (!name.trim()) return { key, error: null };
  if (!key) return { key, error: "Name must include a letter or digit" };
  if (reservedKeys.has(key)) {
    return { key, error: `A status with key '${key}' already exists` };
  }
  return { key, error: null };
}

// The status prompt lives at a fixed, derived path — the "sample" shown to the
// user with the `<key>` / `<status-key>` placeholders filled in. Empty when the
// key is missing (blank name) so callers can gate on it.
function promptPathFor(projectKey: string, statusKey: string): string {
  if (!projectKey || !statusKey) return "";
  return `/projects/${projectKey}/statuses/${statusKey}.md`;
}

export function StatusSettingsModal(props: StatusSettingsModalProps) {
  const mode: "edit" | "new" = props.mode ?? "edit";
  if (mode === "new") {
    return (
      <Modal
        open={props.open}
        onClose={props.onClose}
        title={`New status · ${props.projectRecord.project.name}`}
      >
        <AddStatusForm onClose={props.onClose} projectRecord={props.projectRecord} />
      </Modal>
    );
  }
  return <EditStatusModal {...props} />;
}

function EditStatusModal({
  open,
  onClose,
  projectRecord,
  statusKey: statusKeyProp,
  issueCount: issueCountProp,
}: StatusSettingsModalProps) {
  const statusKey = statusKeyProp ?? "";
  const issueCount = issueCountProp ?? 0;
  const { addToast } = useToast();
  const queryClient = useQueryClient();
  const { data: agents } = useAgents();
  const { data: users } = useUsers();

  const statuses = projectRecord.project.statuses;
  const initialStatus = useMemo(() => {
    const i = statuses.findIndex((s) => s.key === statusKey);
    return i >= 0 ? { status: statuses[i], index: i } : null;
  }, [statuses, statusKey]);
  const index = initialStatus?.index ?? -1;

  const [draft, setDraft] = useState<StatusDefinition | null>(() => initialStatus?.status ?? null);
  const [archiveOpen, setArchiveOpen] = useState(false);

  // Resync local draft whenever the modal is opened against a different
  // status (gear click on another column reuses the same component instance).
  useEffect(() => {
    if (!open) return;
    setDraft(initialStatus?.status ?? null);
    setArchiveOpen(false);
  }, [open, initialStatus]);

  const projectId = projectRecord.project_id;
  const projectKey = projectRecord.project.key as string;

  // The key is derived from the name (never shown), and validated against the
  // OTHER statuses so re-saving without a rename keeps its own key. The backend
  // now accepts key edits, so a rename re-slugs the key end-to-end.
  const reservedKeys = useMemo(
    () => new Set(statuses.filter((_, i) => i !== index).map((s) => s.key as string)),
    [statuses, index],
  );
  const { key: derivedKey, error: keyError } = deriveKeyAndError(draft?.label ?? "", reservedKeys);

  // Seed the inline prompt editor from the status's document as it was opened —
  // a stable path so renaming the status doesn't refetch and discard edits. On
  // save the body is written to the (possibly renamed) derived path below.
  const initialPromptPath = useMemo(() => {
    if (!initialStatus) return null;
    const s = initialStatus.status;
    const existing = s.prompt_path?.trim();
    return existing || promptPathFor(projectKey, s.key as string);
  }, [initialStatus, projectKey]);
  const {
    body: promptBody,
    setBody: setPromptBody,
    loading: promptLoading,
  } = usePromptDocumentBody(initialPromptPath);
  const promptPath = promptPathFor(projectKey, derivedKey);

  // Save covers both edit (status definition update) and archive (cascade
  // through the per-status archive route). The backend cascade handles the
  // issue archives — the client just flips the optimistic statuses list.
  const saveMutation = useMutation({
    mutationFn: async (next: { nextStatuses: StatusDefinition[]; action: "edit" | "archive" }) => {
      const { nextStatuses, action } = next;
      if (action === "edit") {
        // The edit form uses the original `statusKey` as the path
        // segment; a different `draft.key` is a rename.
        const updated = nextStatuses[index];
        return apiClient.updateProjectStatus(projectId, statusKey, updated);
      }
      return apiClient.archiveProjectStatus(projectId, statusKey);
    },
    onMutate: async ({ nextStatuses }) => {
      await queryClient.cancelQueries({ queryKey: PROJECTS_QUERY_KEY });
      const previous = queryClient.getQueryData<ListProjectsResponse>(PROJECTS_QUERY_KEY);
      if (previous) {
        const nextProject = {
          ...projectRecord.project,
          statuses: nextStatuses,
        };
        const next: ListProjectsResponse = {
          projects: applyOptimisticUpsert(previous.projects, projectId, nextProject),
        };
        queryClient.setQueryData<ListProjectsResponse>(PROJECTS_QUERY_KEY, next);
      }
      return { previous };
    },
    onError: (err, _vars, context) => {
      if (context?.previous) {
        queryClient.setQueryData(PROJECTS_QUERY_KEY, context.previous);
      }
      addToast(err instanceof Error ? err.message : "Failed to update status", "error");
    },
    onSuccess: (response) => {
      queryClient.invalidateQueries({ queryKey: PROJECTS_QUERY_KEY });
      queryClient.invalidateQueries({ queryKey: ["project", response.project_id] });
      queryClient.invalidateQueries({ queryKey: ["project-statuses"] });
      queryClient.invalidateQueries({ queryKey: ["paginatedIssues"] });
      queryClient.invalidateQueries({ queryKey: ["documentByPath"] });
      queryClient.invalidateQueries({ queryKey: ["documentPaths"] });
      queryClient.invalidateQueries({ queryKey: ["documentsAtPath"] });
    },
  });

  const onlyStatus = statuses.length <= 1;
  const canArchive = !onlyStatus;
  const archiveTooltip = onlyStatus ? "Cannot archive the only status" : "";

  const handleSave = useCallback(async () => {
    if (!draft || index < 0 || keyError || !draft.label.trim()) return;
    const normalized: StatusDefinition = {
      ...draft,
      key: derivedKey,
      label: draft.label.trim(),
      prompt_path: (promptPath || null) as DocumentPath | null,
    };
    // Write the prompt document at the derived path before the project save so
    // the column never lands pointing at a stale/missing doc.
    if (promptBody.trim() && promptPath) {
      try {
        await upsertPromptDoc(promptPath, promptBody);
      } catch (err) {
        addToast(err instanceof Error ? err.message : "Failed to save prompt", "error");
        return;
      }
    }
    const next = statuses.map((s, i) => (i === index ? normalized : s));
    saveMutation.mutate(
      { nextStatuses: next, action: "edit" },
      {
        onSuccess: () => {
          addToast("Status updated", "success");
          onClose();
        },
      },
    );
  }, [
    draft,
    index,
    derivedKey,
    keyError,
    promptPath,
    promptBody,
    statuses,
    saveMutation,
    addToast,
    onClose,
  ]);

  // Archive flips `archived = true` on the status row; the backend cascade
  // archives every non-archived issue at that status. The optimistic update
  // sets `archived = true` on the affected status so the column drops out of
  // the board's active view before the response lands.
  const handleArchive = useCallback(() => {
    if (!canArchive || index < 0) return;
    const next = statuses.map((s, i) => (i === index ? { ...s, archived: true } : s));
    saveMutation.mutate(
      { nextStatuses: next, action: "archive" },
      {
        onSuccess: () => {
          addToast(
            issueCount > 0
              ? `Status archived (${issueCount} issue(s) cascaded)`
              : "Status archived",
            "success",
          );
          setArchiveOpen(false);
          onClose();
        },
      },
    );
  }, [canArchive, index, statuses, saveMutation, addToast, onClose, issueCount]);

  if (!draft || index < 0) {
    return (
      <Modal open={open} onClose={onClose} title="Status settings">
        <div className={styles.body}>
          <p className={styles.error}>Status "{statusKey}" not found in project.</p>
          <div className={styles.actions}>
            <Button variant="secondary" size="md" onClick={onClose}>
              Close
            </Button>
          </div>
        </div>
      </Modal>
    );
  }

  const title = `Status — ${draft.label || draft.key}`;

  return (
    <Modal open={open} onClose={onClose} title={title}>
      <StatusForm
        draft={draft}
        setDraft={setDraft}
        agents={agents?.map((a) => a.name) ?? []}
        users={users?.map((u) => u.username) ?? []}
        promptBody={promptBody}
        onPromptBodyChange={setPromptBody}
        promptPath={promptPath}
        promptLoading={promptLoading}
      />

      {keyError && draft.label.trim() && (
        <span className={styles.error} data-testid="status-settings-new-error">
          {keyError}
        </span>
      )}

      <div className={styles.actions} data-testid="status-settings-actions">
        <div className={styles.actionsLeft}>
          <Button
            variant="danger-subtle"
            size="md"
            onClick={() => setArchiveOpen(true)}
            disabled={!canArchive || saveMutation.isPending}
            title={archiveTooltip || undefined}
            data-testid="status-settings-archive"
          >
            Archive status
          </Button>
        </div>
        <div className={styles.actionsRight}>
          <Button variant="secondary" size="md" onClick={onClose} disabled={saveMutation.isPending}>
            Cancel
          </Button>
          <Button
            variant="primary"
            size="md"
            onClick={handleSave}
            disabled={saveMutation.isPending || !!keyError || !draft.label.trim()}
            data-testid="status-settings-save"
          >
            {saveMutation.isPending ? "Saving…" : "Save"}
          </Button>
        </div>
      </div>
      <DeleteConfirmModal
        open={archiveOpen}
        onClose={() => setArchiveOpen(false)}
        entityName={draft.label || draft.key}
        entityLabel="Status"
        actionLabel="Archive"
        pendingLabel="Archiving..."
        description={
          issueCount > 0 ? `${issueCount} issue(s) in this status will be archived.` : undefined
        }
        onConfirm={handleArchive}
        isPending={saveMutation.isPending}
      />
    </Modal>
  );
}

interface StatusFormProps {
  draft: StatusDefinition;
  setDraft: (next: StatusDefinition) => void;
  agents: string[];
  users: string[];
  /** Markdown body of the status prompt, edited inline. */
  promptBody: string;
  onPromptBodyChange: (next: string) => void;
  /** Resolved path the prompt is written to (sample with `<>` parts filled in). */
  promptPath: string;
  /** True while the existing prompt document is still loading (edit mode). */
  promptLoading?: boolean;
}

function StatusForm({
  draft,
  setDraft,
  agents,
  users,
  promptBody,
  onPromptBodyChange,
  promptPath,
  promptLoading = false,
}: StatusFormProps) {
  const onEnter = draft.on_enter ?? null;
  const principal = onEnter?.assign_to ?? null;
  const attachForm = onEnter?.attach_form ?? "";
  const [assigneePickerOpen, setAssigneePickerOpen] = useState(false);
  const [idleTimeoutPickerOpen, setIdleTimeoutPickerOpen] = useState(false);
  const [sessionSettingsOpen, setSessionSettingsOpen] = useState(false);
  const [onEnterOpen, setOnEnterOpen] = useState(false);

  // Local display state for the Auto-archive control. Initialized from the
  // draft's persisted seconds via inverse-rendering (largest whole-unit
  // divisor); thereafter the unit selector preserves the displayed value and
  // recomputes seconds, so toggling between days/weeks doesn't surprise the
  // user with a recomputed magnitude.
  const initialAutoSeconds = readAutoArchiveSeconds(draft);
  const [autoArchiveValue, setAutoArchiveValue] = useState<string>(() => {
    if (initialAutoSeconds == null) return "";
    return String(deriveAutoArchiveDisplay(initialAutoSeconds).value);
  });
  const [autoArchiveUnit, setAutoArchiveUnit] = useState<AutoArchiveUnit>(() => {
    if (initialAutoSeconds == null) return "days";
    return deriveAutoArchiveDisplay(initialAutoSeconds).unit;
  });

  const patch = (p: Partial<StatusDefinition>) => setDraft({ ...draft, ...p });

  // ts-rs types `auto_archive_after_seconds` as bigint, but the wire is a
  // plain JSON number; writing a number through satisfies the runtime
  // (JSON.stringify) while we coerce the static type at the boundary.
  const patchAutoArchiveSeconds = (raw: string, unit: AutoArchiveUnit) => {
    const trimmed = raw.trim();
    if (trimmed === "") {
      patch({
        auto_archive_after_seconds: null as unknown as bigint | null,
      });
      return;
    }
    const n = Number(trimmed);
    if (!Number.isFinite(n) || n < 0) {
      patch({
        auto_archive_after_seconds: null as unknown as bigint | null,
      });
      return;
    }
    const seconds = Math.round(n * AUTO_ARCHIVE_UNIT_SECONDS[unit]);
    patch({
      auto_archive_after_seconds: seconds as unknown as bigint | null,
    });
  };

  const onAutoArchiveValueChange = (raw: string) => {
    setAutoArchiveValue(raw);
    patchAutoArchiveSeconds(raw, autoArchiveUnit);
  };
  const onAutoArchiveUnitChange = (unit: AutoArchiveUnit) => {
    setAutoArchiveUnit(unit);
    patchAutoArchiveSeconds(autoArchiveValue, unit);
  };

  // u32 on the wire; empty input clears the cap (None).
  const maxSimultaneousValue =
    draft.max_simultaneous_sessions == null ? "" : String(draft.max_simultaneous_sessions);
  const onMaxSimultaneousChange = (raw: string) => {
    const trimmed = raw.trim();
    if (trimmed === "") {
      patch({ max_simultaneous_sessions: null });
      return;
    }
    const n = Number(trimmed);
    if (!Number.isFinite(n) || n < 0 || !Number.isInteger(n)) return;
    patch({ max_simultaneous_sessions: n });
  };

  const session = draft.session_settings ?? {};

  // Trimmed-empty falls back to clearing the field so the wire doesn't carry a
  // stray "" override. `patch({ session_settings: ... })` collapses to undefined
  // when every field is null so the JSON stays slim.
  const patchSession = (updates: Partial<SessionSettings>) => {
    const merged: SessionSettings = { ...session, ...updates };
    const allEmpty =
      (merged.repo_name ?? null) == null &&
      (merged.remote_url ?? null) == null &&
      (merged.image ?? null) == null &&
      (merged.model ?? null) == null &&
      (merged.branch ?? null) == null &&
      (merged.max_retries ?? null) == null &&
      (merged.cpu_limit ?? null) == null &&
      (merged.memory_limit ?? null) == null &&
      (merged.idle_timeout ?? null) == null &&
      !(merged.secrets && merged.secrets.length > 0);
    patch({ session_settings: allEmpty ? undefined : merged });
  };

  const setSessionString = (key: keyof SessionSettings, raw: string) => {
    patchSession({ [key]: raw === "" ? null : raw } as Partial<SessionSettings>);
  };

  const setSessionMaxRetries = (raw: string) => {
    const trimmed = raw.trim();
    if (trimmed === "") {
      patchSession({ max_retries: null });
      return;
    }
    const n = Number(trimmed);
    if (!Number.isFinite(n) || n < 0 || !Number.isInteger(n)) return;
    patchSession({ max_retries: n });
  };

  // Idle timeout has three discrete modes: Default (None), Infinite, or an
  // explicit seconds count. The select picks the mode; the seconds input is
  // only meaningful in the "seconds" mode and converts on the fly.
  const idleTimeoutMode: "default" | "infinite" | "seconds" = (() => {
    const t = session.idle_timeout;
    if (t == null) return "default";
    if (t.kind === "infinite") return "infinite";
    return "seconds";
  })();
  const idleTimeoutSeconds =
    session.idle_timeout?.kind === "seconds" ? String(session.idle_timeout.value) : "";

  const setIdleTimeoutMode = (mode: "default" | "infinite" | "seconds") => {
    if (mode === "default") {
      patchSession({ idle_timeout: null });
      return;
    }
    if (mode === "infinite") {
      patchSession({ idle_timeout: { kind: "infinite" } });
      return;
    }
    const current =
      session.idle_timeout?.kind === "seconds"
        ? session.idle_timeout.value
        : (60n as unknown as bigint);
    patchSession({ idle_timeout: { kind: "seconds", value: current } });
  };

  const setIdleTimeoutSeconds = (raw: string) => {
    const trimmed = raw.trim();
    if (trimmed === "") {
      patchSession({ idle_timeout: null });
      return;
    }
    const n = Number(trimmed);
    if (!Number.isFinite(n) || n < 1 || !Number.isInteger(n)) return;
    patchSession({
      idle_timeout: { kind: "seconds", value: n as unknown as bigint } as Timeout,
    });
  };

  // The new flat picker doesn't model External, so legacy External
  // assignments render as "Unassigned" in the trigger pill until the user
  // re-picks (the underlying value stays put unless they pick a new row).
  const assigneeView: { name: string; kind: "agent" | "user" } | null = useMemo(() => {
    if (!principal) return null;
    if ("Agent" in principal) return { name: principal.Agent.name, kind: "agent" };
    if ("User" in principal) return { name: principal.User.name, kind: "user" };
    return null;
  }, [principal]);

  const clearAssignee = onEnter?.clear_assignee ?? false;
  const assignToCreator = onEnter?.assign_to_creator ?? false;
  const teardownWork = onEnter?.teardown_work ?? false;

  // `assign_to`, `clear_assignee`, and `assign_to_creator` are pairwise
  // mutually exclusive on the wire; the modal surfaces them as a single
  // three-way radio above the principal-picker row.
  type AssignmentMode = "pick" | "clear" | "creator";
  const assignmentMode: AssignmentMode = assignToCreator
    ? "creator"
    : clearAssignee
      ? "clear"
      : "pick";

  const patchOnEnter = (updates: Partial<StatusOnEnter>) => {
    const next: StatusOnEnter = {
      assign_to: onEnter?.assign_to ?? null,
      attach_form: onEnter?.attach_form ?? null,
      clear_assignee: clearAssignee,
      assign_to_creator: assignToCreator,
      teardown_work: teardownWork,
      ...updates,
    };
    if (
      !next.assign_to &&
      !next.attach_form &&
      !next.clear_assignee &&
      !next.assign_to_creator &&
      !next.teardown_work
    ) {
      patch({ on_enter: null });
      return;
    }
    patch({ on_enter: next });
  };

  // Picking an assignee enforces the mutual-exclusion invariant — the
  // backend's `StatusOnEnter::validate` rejects any two of the trio set at
  // once — by auto-unchecking the other two.
  const setAssign = (next: Principal | null) => {
    patchOnEnter({
      assign_to: next,
      clear_assignee: next ? false : clearAssignee,
      assign_to_creator: next ? false : assignToCreator,
    });
  };

  const setAttachForm = (raw: string) => {
    patchOnEnter({ attach_form: raw ? (raw as DocumentPath) : null });
  };

  // Symmetric to `setAssign` — checking clears the principal and the
  // assign-to-creator flag so the trio can never round-trip as multi-set.
  const setClearAssignee = (next: boolean) => {
    patchOnEnter({
      clear_assignee: next,
      assign_to: next ? null : principal,
      assign_to_creator: next ? false : assignToCreator,
    });
  };

  const setAssignToCreator = (next: boolean) => {
    patchOnEnter({
      assign_to_creator: next,
      assign_to: next ? null : principal,
      clear_assignee: next ? false : clearAssignee,
    });
  };

  const setAssignmentMode = (mode: AssignmentMode) => {
    if (mode === "clear") {
      setClearAssignee(true);
    } else if (mode === "creator") {
      setAssignToCreator(true);
    } else {
      patchOnEnter({ clear_assignee: false, assign_to_creator: false });
    }
  };

  const setTeardownWork = (next: boolean) => {
    patchOnEnter({ teardown_work: next });
  };

  return (
    <div className={styles.body} data-testid="status-settings-form">
      <Input
        label="Name"
        value={draft.label}
        onChange={(e) => patch({ label: e.target.value })}
        placeholder="In progress"
        required
        data-testid="status-settings-label"
      />

      <div className={styles.row}>
        <label className={styles.label}>Color</label>
        <ColorPicker
          value={draft.color}
          onChange={(color) => patch({ color })}
          palette={LABEL_COLOR_PALETTE}
          allowCustom
        />
      </div>

      <div className={styles.flagRow}>
        <label>
          <input
            type="checkbox"
            checked={draft.unblocks_parents}
            onChange={(e) => patch({ unblocks_parents: e.target.checked })}
          />
          Unblocks parents (terminal)
        </label>
        <label>
          <input
            type="checkbox"
            checked={draft.unblocks_dependents}
            onChange={(e) => patch({ unblocks_dependents: e.target.checked })}
          />
          Unblocks dependents
        </label>
        <label>
          <input
            type="checkbox"
            checked={draft.cascades_to_children}
            onChange={(e) => patch({ cascades_to_children: e.target.checked })}
          />
          Cascades to children
        </label>
        <label>
          <input
            type="checkbox"
            checked={draft.interactive ?? false}
            onChange={(e) => patch({ interactive: e.target.checked })}
            data-testid="status-settings-interactive"
          />
          Interactive
        </label>
        <label>
          <input
            type="checkbox"
            checked={draft.suppress_sessions ?? false}
            onChange={(e) => patch({ suppress_sessions: e.target.checked })}
            data-testid="status-settings-suppress-sessions"
          />
          Suppress sessions
        </label>
      </div>

      <div className={styles.autoArchive} data-testid="status-settings-auto-archive">
        <label className={styles.label} htmlFor="status-settings-auto-archive-value">
          Auto-archive after
        </label>
        <div className={styles.autoArchiveInputs}>
          <Input
            id="status-settings-auto-archive-value"
            type="number"
            min={0}
            value={autoArchiveValue}
            onChange={(e) => onAutoArchiveValueChange(e.target.value)}
            placeholder="Off"
            aria-label="Auto-archive duration value"
            data-testid="status-settings-auto-archive-value"
          />
          <Select
            options={[
              { value: "hours", label: "hours" },
              { value: "days", label: "days" },
              { value: "weeks", label: "weeks" },
            ]}
            value={autoArchiveUnit}
            onChange={(e) => onAutoArchiveUnitChange(e.target.value as AutoArchiveUnit)}
            aria-label="Auto-archive duration unit"
            data-testid="status-settings-auto-archive-unit"
          />
        </div>
        <span className={styles.helpText}>
          Issues in this status untouched for longer than this duration are archived automatically
          (by inactivity, not by completion).
        </span>
      </div>

      <div className={styles.sessionSettings}>
        <button
          type="button"
          className={styles.collapsibleSummary}
          aria-expanded={sessionSettingsOpen}
          onClick={() => setSessionSettingsOpen((v) => !v)}
          data-testid="status-settings-session-settings-toggle"
        >
          <span className={styles.collapsibleChevron} aria-hidden="true">
            {sessionSettingsOpen ? (
              <Icons.IconChevronDown size={10} />
            ) : (
              <Icons.IconChevronRight size={10} />
            )}
          </span>
          <span className={styles.onEnterTitle}>Session settings</span>
        </button>
        {sessionSettingsOpen && (
          <div
            className={styles.collapsibleContent}
            data-testid="status-settings-session-settings-content"
          >
            <span className={styles.helpText}>
              Per-status overrides applied when spawning sessions for issues in this status.
              Issue-level settings still win over these. Leave blank to inherit the global / issue
              defaults.
            </span>

            <div className={styles.row}>
              <Input
                label="Max simultaneous sessions"
                type="number"
                min={0}
                step={1}
                value={maxSimultaneousValue}
                onChange={(e) => onMaxSimultaneousChange(e.target.value)}
                placeholder="No cap"
                aria-label="Max simultaneous sessions"
                data-testid="status-settings-max-simultaneous-sessions"
              />
              <span className={styles.helpText}>
                Cap on simultaneously-active sessions (interactive + headless, across all agents)
                for issues in this status. New spawns block until the active count drops below the
                cap.
              </span>
            </div>

            <div className={styles.statusInputs}>
              <Input
                label="CPU limit"
                value={session.cpu_limit ?? ""}
                onChange={(e) => setSessionString("cpu_limit", e.target.value)}
                placeholder="e.g. 500m, 2"
                data-testid="status-settings-cpu-limit"
              />
              <Input
                label="Memory limit"
                value={session.memory_limit ?? ""}
                onChange={(e) => setSessionString("memory_limit", e.target.value)}
                placeholder="e.g. 1Gi, 512Mi"
                data-testid="status-settings-memory-limit"
              />
            </div>

            <div className={styles.statusInputs}>
              <Input
                label="Container image"
                value={session.image ?? ""}
                onChange={(e) => setSessionString("image", e.target.value)}
                placeholder="ghcr.io/org/image:tag"
                data-testid="status-settings-image"
              />
              <Input
                label="Model"
                value={session.model ?? ""}
                onChange={(e) => setSessionString("model", e.target.value)}
                placeholder="e.g. claude-opus-4-7"
                data-testid="status-settings-model"
              />
            </div>

            <div className={styles.statusInputs}>
              <Input
                label="Branch"
                value={session.branch ?? ""}
                onChange={(e) => setSessionString("branch", e.target.value)}
                placeholder="default branch"
                data-testid="status-settings-branch"
              />
              <Input
                label="Max retries"
                type="number"
                min={0}
                step={1}
                value={session.max_retries == null ? "" : String(session.max_retries)}
                onChange={(e) => setSessionMaxRetries(e.target.value)}
                placeholder="Inherit"
                data-testid="status-settings-max-retries"
              />
            </div>

            <div className={styles.idleTimeout} data-testid="status-settings-idle-timeout">
              <label className={styles.label}>Idle timeout</label>
              <div className={styles.idleTimeoutInputs}>
                <Input
                  type="number"
                  min={1}
                  step={1}
                  value={idleTimeoutSeconds}
                  onChange={(e) => setIdleTimeoutSeconds(e.target.value)}
                  disabled={idleTimeoutMode !== "seconds"}
                  placeholder={idleTimeoutMode === "infinite" ? "Never" : "Seconds"}
                  aria-label="Idle timeout seconds"
                  data-testid="status-settings-idle-timeout-seconds"
                />
                <Picker
                  label="Idle timeout"
                  hideLabel
                  open={idleTimeoutPickerOpen}
                  onToggle={() => setIdleTimeoutPickerOpen((v) => !v)}
                  value={
                    idleTimeoutMode === "default" ? (
                      <span className={styles.pillEmpty}>Server default</span>
                    ) : idleTimeoutMode === "infinite" ? (
                      <span>Never</span>
                    ) : (
                      <span>Custom</span>
                    )
                  }
                  data-testid="status-settings-idle-timeout-mode"
                >
                  <PickerRow
                    active={idleTimeoutMode === "default"}
                    onClick={() => {
                      setIdleTimeoutMode("default");
                      setIdleTimeoutPickerOpen(false);
                    }}
                  >
                    <span>Server default</span>
                    <span className={styles.popSpacer} />
                  </PickerRow>
                  <PickerRow
                    active={idleTimeoutMode === "seconds"}
                    onClick={() => {
                      setIdleTimeoutMode("seconds");
                      setIdleTimeoutPickerOpen(false);
                    }}
                  >
                    <span>Custom (seconds)</span>
                    <span className={styles.popSpacer} />
                  </PickerRow>
                  <PickerRow
                    active={idleTimeoutMode === "infinite"}
                    onClick={() => {
                      setIdleTimeoutMode("infinite");
                      setIdleTimeoutPickerOpen(false);
                    }}
                  >
                    <span>Never</span>
                    <span className={styles.popSpacer} />
                  </PickerRow>
                </Picker>
              </div>
              <span className={styles.helpText}>
                Per-session idle timeout for sessions spawned for this status. "Server default"
                falls back to the global config; "Never" lets long-running dev-preview sessions stay
                alive.
              </span>
            </div>
          </div>
        )}
      </div>

      <div className={styles.onEnter}>
        <button
          type="button"
          className={styles.collapsibleSummary}
          aria-expanded={onEnterOpen}
          onClick={() => setOnEnterOpen((v) => !v)}
          data-testid="status-settings-on-enter-toggle"
        >
          <span className={styles.collapsibleChevron} aria-hidden="true">
            {onEnterOpen ? (
              <Icons.IconChevronDown size={10} />
            ) : (
              <Icons.IconChevronRight size={10} />
            )}
          </span>
          <span className={styles.onEnterTitle}>On enter</span>
        </button>
        {onEnterOpen && (
          <div className={styles.collapsibleContent} data-testid="status-settings-on-enter-content">
            <div data-testid="status-settings-assignee">
              <fieldset
                className={styles.assigneeMode}
                data-testid="status-settings-assignment-mode"
              >
                <legend className={styles.label}>Assignee on enter</legend>
                <label>
                  <input
                    type="radio"
                    name="status-settings-assignment-mode"
                    checked={assignmentMode === "pick"}
                    onChange={() => setAssignmentMode("pick")}
                    data-testid="status-settings-assignment-mode-pick"
                  />
                  Pick
                </label>
                <label>
                  <input
                    type="radio"
                    name="status-settings-assignment-mode"
                    checked={assignmentMode === "clear"}
                    onChange={() => setAssignmentMode("clear")}
                    data-testid="status-settings-clear-assignee"
                  />
                  Clear assignee
                </label>
                <label>
                  <input
                    type="radio"
                    name="status-settings-assignment-mode"
                    checked={assignmentMode === "creator"}
                    onChange={() => setAssignmentMode("creator")}
                    data-testid="status-settings-assign-to-creator"
                  />
                  Assign to creator
                </label>
              </fieldset>
              <div
                className={assignmentMode === "pick" ? undefined : styles.assigneePickerDisabled}
              >
                <Picker
                  label="Assign to"
                  open={assignmentMode === "pick" && assigneePickerOpen}
                  onToggle={() => {
                    if (assignmentMode === "pick") {
                      setAssigneePickerOpen((v) => !v);
                    }
                  }}
                  wide
                  value={
                    assignmentMode === "creator" ? (
                      <span className={styles.pillContent}>
                        <span>Issue creator</span>
                      </span>
                    ) : assignmentMode === "clear" ? (
                      <span className={styles.pillEmpty}>Unassigned</span>
                    ) : assigneeView ? (
                      <span className={styles.pillContent}>
                        <Avatar
                          name={assigneeView.name}
                          kind={assigneeView.kind === "agent" ? "agent" : "human"}
                          size="md"
                        />
                        <span>{assigneeView.name}</span>
                      </span>
                    ) : (
                      <span className={styles.pillEmpty}>Unassigned</span>
                    )
                  }
                >
                  <PickerRow
                    active={!principal}
                    onClick={() => {
                      setAssign(null);
                      setAssigneePickerOpen(false);
                    }}
                  >
                    <span className={styles.pillEmpty}>Unassigned</span>
                    <span className={styles.popSpacer} />
                  </PickerRow>
                  {agents.length > 0 && (
                    <>
                      <div className={styles.popSection}>Agents</div>
                      {agents.map((name) => (
                        <PickerRow
                          key={`agents/${name}`}
                          active={
                            !!principal && "Agent" in principal && principal.Agent.name === name
                          }
                          onClick={() => {
                            setAssign({ Agent: { name } });
                            setAssigneePickerOpen(false);
                          }}
                        >
                          <Avatar name={name} kind="agent" size="md" />
                          <span>{name}</span>
                          <span className={styles.popSpacer} />
                        </PickerRow>
                      ))}
                    </>
                  )}
                  {users.length > 0 && (
                    <>
                      <div className={styles.popSection}>Users</div>
                      {users.map((name) => (
                        <PickerRow
                          key={`users/${name}`}
                          active={
                            !!principal && "User" in principal && principal.User.name === name
                          }
                          onClick={() => {
                            setAssign({ User: { name } });
                            setAssigneePickerOpen(false);
                          }}
                        >
                          <Avatar name={name} kind="human" size="md" />
                          <span>{name}</span>
                          <span className={styles.popSpacer} />
                        </PickerRow>
                      ))}
                    </>
                  )}
                </Picker>
              </div>
            </div>
            <Input
              label="Attach form"
              value={attachForm}
              onChange={(e) => setAttachForm(e.target.value)}
              placeholder="/forms/review.yaml"
            />
            <div className={styles.flagRow}>
              <label>
                <input
                  type="checkbox"
                  checked={teardownWork}
                  onChange={(e) => setTeardownWork(e.target.checked)}
                  data-testid="status-settings-teardown-work"
                />
                Teardown work
              </label>
            </div>
            <span className={styles.helpText}>
              "Pick", "Clear assignee", and "Assign to creator" are mutually exclusive — the picker
              is only interactive in Pick mode.
            </span>
          </div>
        )}
      </div>

      <div className={styles.row}>
        <Textarea
          label="Prompt"
          value={promptBody}
          onChange={(e) => onPromptBodyChange(e.target.value)}
          placeholder={
            promptLoading
              ? "Loading prompt…"
              : `# Prompt for this status\n\nWrite the prompt the assignee sees on enter.`
          }
          rows={12}
          disabled={promptLoading}
          data-testid="status-settings-prompt-body"
        />
        <span className={styles.readOnlyNote} data-testid="status-settings-prompt-path">
          Saved to {promptPath || "/projects/<key>/statuses/<status-key>.md"}
        </span>
      </div>
    </div>
  );
}

interface AddStatusFormProps {
  onClose: () => void;
  projectRecord: ProjectRecord;
}

// "Add status" flow. Reuses the same `StatusForm` as the edit modal so the two
// look and behave alike — Name, color, flags, on-enter, and the inline prompt
// editor are all here. The only edit-mode controls dropped are the ones that
// make no sense before the status exists: delete and move-and-delete. The key
// is derived from the name (never shown), and the prompt body is written to the
// derived path inline, same as edit mode.
function AddStatusForm({ onClose, projectRecord }: AddStatusFormProps) {
  const { addToast } = useToast();
  const queryClient = useQueryClient();
  const { data: agents } = useAgents();
  const { data: users } = useUsers();
  const statuses = projectRecord.project.statuses;
  const projectId = projectRecord.project_id;
  const projectKey = projectRecord.project.key as string;

  const [draft, setDraft] = useState<StatusDefinition>(() => blankStatus(statuses.length));
  const [promptBody, setPromptBody] = useState("");

  const existingKeys = useMemo(() => new Set(statuses.map((s) => s.key as string)), [statuses]);
  const { key: derivedKey, error: keyError } = deriveKeyAndError(draft.label, existingKeys);
  const labelMissing = !draft.label.trim();
  const promptPath = promptPathFor(projectKey, derivedKey);

  const saveMutation = useMutation({
    mutationFn: async (status: StatusDefinition) => {
      // Write the prompt doc at the derived path first (only when non-empty),
      // then append the status via the per-status endpoint.
      if (promptBody.trim() && status.prompt_path) {
        await upsertPromptDoc(status.prompt_path as string, promptBody);
      }
      return apiClient.createProjectStatus(projectId, status);
    },
    onMutate: async (status) => {
      await queryClient.cancelQueries({ queryKey: PROJECTS_QUERY_KEY });
      const previous = queryClient.getQueryData<ListProjectsResponse>(PROJECTS_QUERY_KEY);
      if (previous) {
        const nextProject = {
          ...projectRecord.project,
          statuses: [...statuses, status],
        };
        const next: ListProjectsResponse = {
          projects: applyOptimisticUpsert(previous.projects, projectId, nextProject),
        };
        queryClient.setQueryData<ListProjectsResponse>(PROJECTS_QUERY_KEY, next);
      }
      return { previous };
    },
    onError: (err, _vars, context) => {
      if (context?.previous) {
        queryClient.setQueryData(PROJECTS_QUERY_KEY, context.previous);
      }
      addToast(err instanceof Error ? err.message : "Failed to add status", "error");
    },
    onSuccess: (response) => {
      queryClient.invalidateQueries({ queryKey: PROJECTS_QUERY_KEY });
      queryClient.invalidateQueries({
        queryKey: ["project", response.project_id],
      });
      queryClient.invalidateQueries({ queryKey: ["project-statuses"] });
      queryClient.invalidateQueries({ queryKey: ["documentByPath"] });
      queryClient.invalidateQueries({ queryKey: ["documentPaths"] });
      queryClient.invalidateQueries({ queryKey: ["documentsAtPath"] });
      addToast("Status added", "success");
      onClose();
    },
  });

  const canSave = !keyError && !labelMissing && !!derivedKey && !saveMutation.isPending;

  const handleSave = useCallback(() => {
    if (!canSave) return;
    const status: StatusDefinition = {
      ...draft,
      key: derivedKey,
      label: draft.label.trim(),
      prompt_path: (promptPath || null) as DocumentPath | null,
    };
    saveMutation.mutate(status);
  }, [canSave, draft, derivedKey, promptPath, saveMutation]);

  return (
    <>
      <StatusForm
        draft={draft}
        setDraft={setDraft}
        agents={agents?.map((a) => a.name) ?? []}
        users={users?.map((u) => u.username) ?? []}
        promptBody={promptBody}
        onPromptBodyChange={setPromptBody}
        promptPath={promptPath}
      />

      <div className={styles.actions} data-testid="status-settings-actions">
        <div className={styles.actionsLeft}>
          {keyError && draft.label.trim() && (
            <span className={styles.error} data-testid="status-settings-new-error">
              {keyError}
            </span>
          )}
        </div>
        <div className={styles.actionsRight}>
          <Button variant="secondary" size="md" onClick={onClose} disabled={saveMutation.isPending}>
            Cancel
          </Button>
          <Button
            variant="primary"
            size="md"
            onClick={handleSave}
            disabled={!canSave}
            data-testid="status-settings-save"
          >
            {saveMutation.isPending ? "Adding…" : "Add status"}
          </Button>
        </div>
      </div>
    </>
  );
}
